apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: horizontalpodautoscalers.autoscaling
spec:
  group: autoscaling
  versions:
    - name: v2beta2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
  scope: Namespaced
  names:
    plural: horizontalpodautoscalers
    singular: horizontalpodautoscaler
    kind: HorizontalPodAutoscaler
    shortNames:
      - hpa

