apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: recipe-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: recipe-app-deployment  # Replace with your deployment name
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

