name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Build and Push Docker Image
      run: |
        docker build -t your-username/my-app .
        docker tag your-username/my-app your-username/my-app:latest
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u your-username --password-stdin
        docker push your-username/my-app:latest

    - name: Deploy to Kubernetes
      run: kubectl apply -f deployment.yaml

